services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Rootr00t
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - mssql_network
    mem_limit: 2g
    cpus: "2.0"

  entitybenchmark:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mssql_network

networks:
  mssql_network:
