services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: benchmark_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Rootr00t
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - benchmark_network
    mem_limit: 2g
    cpus: "2.0"

  entitybenchmark:
    build:
      context: ../EntityBenchmark
      dockerfile: Dockerfile
    container_name: entity_benchmark
    depends_on:
      - mssql
    networks:
      - benchmark_network
    mem_limit: 2g
    cpus: "2.0"

  dapperbenchmark:
    build:
      context: ../DapperBenchmark
      dockerfile: Dockerfile
    container_name: dapper_benchmark
    depends_on:
      - mssql
    networks:
      - benchmark_network
    mem_limit: 2g
    cpus: "2.0"

networks:
  benchmark_network:
    driver: bridge