services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Rootr00t
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql
    networks:
      - mssql_network
    mem_limit: 2g
    cpus: "2.0"

networks:
  mssql_network:
