USE DapperDatabase;

CREATE TABLE Parent (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL
);

CREATE TABLE Child (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    ParentId INT NOT NULL FOREIGN KEY REFERENCES Parent(Id)
);
